# -*- coding: utf-8 -*-
"""phase_3_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gv4_ERH4C6VLrYTQTrVTij5nqGPdi1Sc
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from scipy.stats import (
    pearsonr,
    spearmanr,
    shapiro
)

from sklearn.preprocessing import StandardScaler

import warnings

warnings.filterwarnings("ignore")

!pip install supabase

# Kena connect dengan supabase
from supabase import create_client

SUPABASE_URL = "https://dgczwrzkjgqyacuuvjzw.supabase.co"

SUPABASE_KEY = "sb_publishable_QdSenIu7B_7awGCPU1bwew_5yXg-QQv"

supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)

print("Connected to Supabase")

def load_table(table_name, batch_size=1000):

    all_rows = []

    start = 0

    while True:

        response = (
            supabase
            .table(table_name)
            .select("*")
            .range(start, start + batch_size - 1)
            .execute()
        )

        rows = response.data

        if not rows:
            break

        all_rows.extend(rows)

        start += batch_size

        print(
            f"{table_name}: "
            f"{len(all_rows)} rows loaded"
        )

    return pd.DataFrame(all_rows)

tables = [

    "agri_employed_2023",

    "crop_production_2023",

    "pahang_poverty_district",

    "pahang_income_district",

    "pahang_labour_district",

    "pahang_amenities",

    "pahang_population",

    "pahang_enrolment_school_district"

]

datasets = {}

for table in tables:

    df = load_table(table)

    datasets[table] = df

    print(
        f"✅ {table}: {df.shape}"
    )

data = {}

for table in tables:
    data[table] = load_table(table)
    print(f"okay {table}: {data[table].shape}")

district_mapping = {

    "Kuala Lipis": "Lipis",

    "Cameron Highland":
        "Cameron Highlands",

    "All Districts": np.nan,

    "Total": np.nan
}


def clean_district(df):

    if "district" in df.columns:

        df["district"] = (

            df["district"]

            .astype(str)

            .str.strip()

            .replace(district_mapping)

        )

        df = df.dropna(
            subset=["district"]
        )

    return df


for name in datasets:

    datasets[name] = clean_district(
        datasets[name]
    )

print("District names standardized.")

for name, df in datasets.items():

    if "district" in df.columns:

        print("\n" + "=" * 50)

        print(name)

        print(
            sorted(
                df["district"]
                .unique()
            )
        )

inventory = []

for name, df in datasets.items():

    inventory.append({

        "dataset":
            name,

        "rows":
            len(df),

        "columns":
            len(df.columns),

        "missing_values":
            df.isnull()
            .sum()
            .sum(),

        "duplicate_rows":
            df.duplicated()
            .sum()

    })

inventory = pd.DataFrame(
    inventory
)

inventory

for name, df in datasets.items():

    print("\n")

    print("=" * 60)

    print(name)

    if "year" in df.columns:

        print(
            "Years:"
        )

        print(
            sorted(
                df["year"]
                .unique()
            )
        )

    if "date" in df.columns:

        print(
            "Dates:"
        )

        print(
            sorted(
                df["date"]
                .astype(str)
                .unique()
            )[:10]
        )

# ni nak tengok indicator
employment_variables = {

    "labour_force_000":
        "Labour force",

    "employed_000":
        "Employed",

    "unemployed_000":
        "Unemployed",

    "outside_lf_000":
        "Outside labour force",

    "participation_rate_pct":
        "Labour force participation",

    "unemployment_rate_pct":
        "Unemployment rate",

    "employment_pop_ratio_pct":
        "Employment-population ratio",

    "income_mean_rm":
        "Mean household income",

    "income_median_rm":
        "Median household income",

    "total_employment":
        "Agricultural employment",

    "avg_annual_salary_rm":
        "Agricultural salary"

}

pd.DataFrame(

    employment_variables.items(),

    columns=[

        "Variable",

        "Description"

    ]

)

labour = datasets[
    "pahang_labour_district"
]

labour.describe().T

districts = sorted(

    labour["district"]

    .unique()

)

districts

agri = datasets["agri_employed_2023"].copy()

agri = agri[agri["district"].notna()]

agri["total_employment"] = (

    agri["total_employment"]

    .astype(str)

    .str.replace(",", "")

    .astype(float)

)

agri["avg_annual_salary_rm"] = (

    agri["avg_annual_salary_rm"]

    .astype(str)

    .str.replace(",", "")

    .str.replace(".", "", regex=False)

    .astype(float)

)

agri

poverty = datasets["pahang_poverty_district"].copy()

labour = datasets["pahang_labour_district"].copy()

income = datasets["pahang_income_district"].copy()

analysis_df = (

    poverty

    .merge(

        labour,

        on=["district", "year"]

    )

    .merge(

        income,

        on=["district", "year"]

    )

)

analysis_df.shape

analysis_df.info()

analysis_df.describe().T

# okay ni nak buat dataset personal untuk setiap daerah, jadinya kita pecah 11
district_data = {}

for district in districts:

    district_data[district] = (

        analysis_df[

            analysis_df["district"] == district

        ]

        .copy()

    )

print(

    len(district_data),

    "district datasets created."

)

# check jap
district_data["Kuantan"]

# correlation
import numpy as np
import pandas as pd

variables = [
    "labour_force_000",
    "employed_000",
    "unemployed_000",
    "participation_rate_pct",
    "unemployment_rate_pct",
    "employment_pop_ratio_pct",
    "income_mean_rm",
    "income_median_rm"
]

results = []

for district in sorted(analysis_df["district"].unique()):

    district_df = analysis_df[
        analysis_df["district"] == district
    ]

    for variable in variables:

        correlation = district_df[
            variable
        ].corr(
            district_df[
                "poverty_absolute_pct"
            ]
        )

        results.append({
            "district": district,
            "variable": variable,
            "correlation": correlation
        })

correlation_df = pd.DataFrame(results)

correlation_df

# nak clarify strength
def classify_relationship(r):

    if pd.isna(r):
        return "No relationship"

    r = abs(r)

    if r >= 0.8:
        return "Strong"

    elif r >= 0.5:
        return "Moderate"

    else:
        return "Weak"


correlation_df["strength"] = (
    correlation_df["correlation"]
    .apply(classify_relationship)
)

correlation_df

# ni direction pulak
def relationship_direction(r):

    if pd.isna(r):
        return "Unknown"

    if r > 0:
        return "Positive"

    if r < 0:
        return "Negative"

    return "No relationship"


correlation_df["direction"] = (
    correlation_df["correlation"]
    .apply(relationship_direction)
)

correlation_df

# nak rank
ranked_df = (
    correlation_df
    .sort_values(
        ["district", "correlation"],
        ascending=[True, False]
    )
)

ranked_df

# nak tengok 2 paling top
selected_variables = (
    correlation_df
    .iloc[
        correlation_df
        .groupby("district")["correlation"]
        .apply(
            lambda x: x.abs().nlargest(2)
        )
        .index
        .get_level_values(1)
    ]
)

selected_variables

for district in sorted(
    selected_variables["district"].unique()
):

    print("\n" + "=" * 60)

    print(district)

    display(

        selected_variables[
            selected_variables["district"]
            == district
        ][[
            "variable",
            "correlation",
            "strength",
            "direction"
        ]]

    )

selected_df = pd.DataFrame({

    "district": [
        "Bentong",
        "Bera",
        "Cameron Highlands",
        "Jerantut",
        "Kuantan",
        "Lipis",
        "Maran",
        "Pekan",
        "Raub",
        "Rompin",
        "Temerloh"
    ],

    "indicator_1": [
        "employment_pop_ratio_pct",
        "employment_pop_ratio_pct",
        "employment_pop_ratio_pct",
        "unemployed_000",
        "income_mean_rm",
        "unemployed_000",
        "labour_force_000",
        "participation_rate_pct",
        "participation_rate_pct",
        "employment_pop_ratio_pct",
        "employed_000"
    ],

    "indicator_2": [
        "income_mean_rm",
        "participation_rate_pct",
        "unemployment_rate_pct",
        "participation_rate_pct",
        "labour_force_000",
        "participation_rate_pct",
        "employed_000",
        "employment_pop_ratio_pct",
        "unemployed_000",
        "participation_rate_pct",
        "labour_force_000"
    ]

})

selected_df

"""***INDICATOR***"""

economic_profile = {
    "Income-driven": [
        "Bentong",
        "Kuantan"
    ],

    "Participation-driven": [
        "Bera",
        "Pekan",
        "Raub",
        "Rompin"
    ],

    "Unemployment-driven": [
        "Jerantut",
        "Lipis"
    ],

    "Labour-driven": [
        "Maran",
        "Temerloh"
    ],

    "Employment-structure-driven": [
        "Cameron Highlands"
    ]
}

profile_lookup = {}

for profile, districts in economic_profile.items():

    for district in districts:

        profile_lookup[district] = profile


summary_df = selected_variables.copy()

summary_df = (
    summary_df
    .sort_values(
        ["district", "correlation"],
        ascending=[True, False]
    )
)

summary_df["rank"] = (
    summary_df
    .groupby("district")
    .cumcount() + 1
)

driver_1 = (
    summary_df[summary_df["rank"] == 1]
    [["district", "variable"]]
    .rename(
        columns={
            "variable": "main_driver"
        }
    )
)

driver_2 = (
    summary_df[summary_df["rank"] == 2]
    [["district", "variable"]]
    .rename(
        columns={
            "variable": "secondary_driver"
        }
    )
)

district_summary = (
    driver_1
    .merge(driver_2, on="district")
)

district_summary["economic_profile"] = (
    district_summary["district"]
    .map(profile_lookup)
)

district_summary

# ni yang lawa sikit
variable_names = {
    "income_mean_rm": "Mean income",
    "income_median_rm": "Median income",
    "labour_force_000": "Labour force",
    "employed_000": "Employed population",
    "unemployed_000": "Unemployed population",
    "participation_rate_pct": "Labour participation rate",
    "unemployment_rate_pct": "Unemployment rate",
    "employment_pop_ratio_pct": "Employment-population ratio"
}

district_summary["main_driver"] = (
    district_summary["main_driver"]
    .replace(variable_names)
)

district_summary["secondary_driver"] = (
    district_summary["secondary_driver"]
    .replace(variable_names)
)

district_summary

"""***NI PART LINEAR/NON-LINEAR***"""

top_variables = {

    "Bentong": [
        "employment_pop_ratio_pct",
        "income_mean_rm"
    ],

    "Bera": [
        "employment_pop_ratio_pct",
        "participation_rate_pct"
    ],

    "Cameron Highlands": [
        "employment_pop_ratio_pct",
        "unemployment_rate_pct"
    ],

    "Jerantut": [
        "unemployed_000",
        "participation_rate_pct"
    ],

    "Kuantan": [
        "income_mean_rm",
        "labour_force_000"
    ],

    "Lipis": [
        "unemployed_000",
        "participation_rate_pct"
    ],

    "Maran": [
        "labour_force_000",
        "employed_000"
    ],

    "Pekan": [
        "participation_rate_pct",
        "employment_pop_ratio_pct"
    ],

    "Raub": [
        "participation_rate_pct",
        "unemployed_000"
    ],

    "Rompin": [
        "employment_pop_ratio_pct",
        "participation_rate_pct"
    ],

    "Temerloh": [
        "employed_000",
        "labour_force_000"
    ]
}

import matplotlib.pyplot as plt

for district, variables in top_variables.items():

    district_df = analysis_df[
        analysis_df["district"] == district
    ]

    print("\n" + "=" * 60)
    print(district)

    for variable in variables:

        plt.figure(figsize=(6, 5))

        x = district_df[variable]
        y = district_df["poverty_absolute_pct"]

        plt.scatter(x, y)

        plt.plot(x, y)

        for _, row in district_df.iterrows():

            plt.annotate(

                str(row["year"]),

                (row[variable],
                 row["poverty_absolute_pct"])

            )

        plt.xlabel(variable)

        plt.ylabel(
            "poverty_absolute_pct"
        )

        plt.title(
            f"{district}: {variable}"
        )

        plt.grid(True)

        plt.show()

from scipy.stats import pearsonr
from scipy.stats import spearmanr

results = []

for district, variables in top_variables.items():

    district_df = analysis_df[
        analysis_df["district"] == district
    ]

    for variable in variables:

        pearson, _ = pearsonr(

            district_df[variable],

            district_df[
                "poverty_absolute_pct"
            ]

        )

        spearman, _ = spearmanr(

            district_df[variable],

            district_df[
                "poverty_absolute_pct"
            ]

        )

        results.append({

            "district": district,

            "variable": variable,

            "pearson": pearson,

            "spearman": spearman

        })

relationship_test = pd.DataFrame(
    results
)

relationship_test

"""*ATTN: Due to the limited number of observations (2019, 2022, and 2024), the relationship analysis is exploratory and intended to identify potential district-specific employment indicators rather than establish definitive statistical relationships.*

| District          | Main indicator              | Relationship        |
| ----------------- | --------------------------- | ------------------- |
| Bentong           | Employment-population ratio | Linear              |
| Bentong           | Mean income                 | Linear              |
| Bera              | Employment-population ratio | Possibly non-linear |
| Bera              | Participation rate          | Possibly non-linear |
| Cameron Highlands | Employment-population ratio | Non-linear          |
| Cameron Highlands | Unemployment rate           | Linear              |
| Jerantut          | Unemployed population       | Mostly linear       |
| Jerantut          | Participation rate          | Linear              |
| Kuantan           | Mean income                 | Linear              |
| Kuantan           | Labour force                | Non-linear          |
| Lipis             | Unemployed population       | Linear              |
| Lipis             | Participation rate          | Mostly linear       |
| Maran             | Labour force                | Linear              |
| Maran             | Employed population         | Linear              |
| Pekan             | Participation rate          | Linear              |
| Pekan             | Employment-population ratio | Linear              |
| Raub              | Participation rate          | Linear              |
| Raub              | Unemployed population       | Linear              |
| Rompin            | Employment-population ratio | Linear              |
| Rompin            | Participation rate          | Linear              |
| Temerloh          | Employed population         | Linear              |
| Temerloh          | Labour force                | Linear              |

The relationship between employment indicators and household poverty varies across Pahang's districts. Income-related indicators demonstrated stronger associations in urban districts such as Kuantan and Bentong, whereas labour participation indicators were more influential in Bera, Pekan, Raub, and Rompin. Unemployment-related indicators showed stronger relationships in Jerantut and Lipis. These findings support the hypothesis that unemployment alone is an insufficient proxy for household economic hardship.
"""

# ni significance
from scipy.stats import pearsonr

significance_results = []

variables = [
    "labour_force_000",
    "employed_000",
    "unemployed_000",
    "outside_lf_000",
    "participation_rate_pct",
    "unemployment_rate_pct",
    "employment_pop_ratio_pct",
    "income_mean_rm",
    "income_median_rm"
]

for district in analysis_df["district"].unique():

    district_df = analysis_df[
        analysis_df["district"] == district
    ]

    for variable in variables:

        r, p = pearsonr(
            district_df[variable],
            district_df["poverty_absolute_pct"]
        )

        significance_results.append({

            "district": district,
            "variable": variable,
            "correlation": round(r, 4),
            "p_value": round(p, 4),
            "significant": p < 0.05

        })

significance_df = pd.DataFrame(
    significance_results
)

significance_df.sort_values(
    ["district", "p_value"]
).head(50)

significant_variables = significance_df[
    significance_df["significant"] == True
]

significant_variables

"""## Significance Testing

The significance test showed that only the employment-population ratio in Bentong and the unemployed population in Lipis achieved statistical significance at the 5% level.

However, the majority of variables demonstrated strong correlation coefficients despite having non-significant p-values.

This outcome is likely attributable to the limited number of observations available for each district (2019, 2022, and 2024).

Therefore, the correlation coefficients were retained as exploratory evidence for variable selection in the subsequent development of the District Vulnerability Index.
"""

# ni lain
comparison = analysis_df[[
    "district",
    "year",
    "poverty_absolute_pct",
    "unemployment_rate_pct",
    "income_mean_rm",
    "participation_rate_pct",
    "employment_pop_ratio_pct"
]]

comparison.sort_values(
    ["year", "poverty_absolute_pct"],
    ascending=[True, False]
)

# ini miskin tapi tak ramai menganggur
poverty_median = (
    analysis_df["poverty_absolute_pct"].median()
)

unemployment_median = (
    analysis_df["unemployment_rate_pct"].median()
)

comparison["poverty_group"] = comparison[
    "poverty_absolute_pct"
].apply(
    lambda x:
    "High" if x >= poverty_median else "Low"
)

comparison["unemployment_group"] = comparison[
    "unemployment_rate_pct"
].apply(
    lambda x:
    "High" if x >= unemployment_median else "Low"
)

comparison[
    (comparison["poverty_group"] == "High")
    &
    (comparison["unemployment_group"] == "Low")
]

# ini chart nak tengok
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))

for _, row in analysis_df.iterrows():

    plt.scatter(
        row["unemployment_rate_pct"],
        row["poverty_absolute_pct"]
    )

    plt.annotate(
        f"{row['district']} ({row['year']})",
        (
            row["unemployment_rate_pct"],
            row["poverty_absolute_pct"]
        )
    )

plt.xlabel("Unemployment rate (%)")

plt.ylabel("Poverty rate (%)")

plt.title(
    "Household poverty versus unemployment across Pahang districts"
)

plt.grid()

plt.show()

# LFPR vs Poverty — Pooled Pahang

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

plt.scatter(
    analysis_df["participation_rate_pct"],
    analysis_df["poverty_absolute_pct"]
)

for _, row in analysis_df.iterrows():
    plt.annotate(
        f"{row['district']} ({row['year']})",
        (
            row["participation_rate_pct"],
            row["poverty_absolute_pct"]
        ),
        fontsize=8
    )

plt.xlabel("Labour Force Participation Rate (%)")
plt.ylabel("Absolute Poverty Rate (%)")
plt.title(
    "Labour Force Participation Rate vs Absolute Poverty Rate\n"
    "Pahang Districts, 2019–2024"
)

plt.grid(True)
plt.show()

"""District-year observations with higher labour force participation generally tend to have lower poverty rates.

*   Cameron Highlands has relatively high LFPR (70%-72%) and relatively low poverty in 2019 & 2022
*   Bera has low LFPR (53–54%) and relatively high poverty in 2022/2024.
* Lipis also has low LFPR (54%) and high poverty.
* Pekan 2022/2024 has relatively high poverty despite LFPR around 65%, showing that the relationship isn't perfectly linear.
* Rompin 2022 is an obvious high-poverty observation despite LFPR around 59%.
"""

# Additional descriptive statistics: Median and IQR

eda_variables = [
    "poverty_absolute_pct",
    "unemployment_rate_pct",
    "participation_rate_pct"
]

descriptive_summary = []

for variable in eda_variables:

    series = analysis_df[variable].dropna()

    descriptive_summary.append({
        "Variable": variable,
        "Mean": series.mean(),
        "Median": series.median(),
        "SD": series.std(),
        "IQR": series.quantile(0.75) - series.quantile(0.25),
        "Minimum": series.min(),
        "Maximum": series.max()
    })

descriptive_summary = pd.DataFrame(
    descriptive_summary
)

descriptive_summary.round(3)

import matplotlib.pyplot as plt

for variable in eda_variables:

    plt.figure(figsize=(7, 5))

    plt.hist(
        analysis_df[variable].dropna(),
        bins=10
    )

    plt.xlabel(variable)
    plt.ylabel("Frequency")

    plt.title(
        f"Distribution of {variable}"
    )

    plt.grid(True, alpha=0.3)

    plt.show()

# Shapiro-Wilk
from scipy.stats import shapiro

normality_results = []

for variable in eda_variables:

    series = analysis_df[variable].dropna()

    statistic, p_value = shapiro(series)

    normality_results.append({
        "Variable": variable,
        "Shapiro_W": statistic,
        "p_value": p_value,
        "Normal_at_5pct": p_value >= 0.05
    })

normality_df = pd.DataFrame(
    normality_results
)

normality_df.round(4)

"""## Normality Assessment

The Shapiro-Wilk test was conducted to assess the distributional characteristics of the main variables used in Objective 1.

Absolute poverty rate did not show evidence of non-normality (W = 0.9651, p = 0.3571). However, both unemployment rate (W = 0.9302, p = 0.0354) and labour force participation rate (W = 0.9219, p = 0.0206) showed statistically significant departures from normality at the 5% significance level.

Therefore, the analysis does not rely solely on Pearson correlation. Spearman's rank correlation and Kendall's tau are also used as non-parametric measures to assess the robustness of the observed relationships.
"""

# IQR Outlier Detection

outlier_results = []

for variable in eda_variables:

    series = analysis_df[variable].dropna()

    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = analysis_df[
        (analysis_df[variable] < lower_bound) |
        (analysis_df[variable] > upper_bound)
    ][[
        "district",
        "year",
        variable
    ]]

    print("\n" + "=" * 70)
    print(variable)

    print(f"Q1: {Q1:.3f}")
    print(f"Q3: {Q3:.3f}")
    print(f"IQR: {IQR:.3f}")
    print(f"Lower bound: {lower_bound:.3f}")
    print(f"Upper bound: {upper_bound:.3f}")

    print("\nPotential outliers:")

    if outliers.empty:
        print("No potential outliers detected.")
    else:
        display(outliers)

# Bera investigation
bera_data = analysis_df[
    analysis_df["district"] == "Bera"
].sort_values("year")

bera_data

bera_comparison = []

for year in sorted(analysis_df["year"].unique()):

    year_data = analysis_df[
        analysis_df["year"] == year
    ]

    bera_row = year_data[
        year_data["district"] == "Bera"
    ]

    if len(bera_row) > 0:

        bera_comparison.append({

            "year": year,

            "Bera_poverty":
                bera_row["poverty_absolute_pct"].iloc[0],

            "Pahang_median_poverty":
                year_data[
                    "poverty_absolute_pct"
                ].median(),

            "Bera_unemployment":
                bera_row[
                    "unemployment_rate_pct"
                ].iloc[0],

            "Pahang_median_unemployment":
                year_data[
                    "unemployment_rate_pct"
                ].median(),

            "Bera_LFPR":
                bera_row[
                    "participation_rate_pct"
                ].iloc[0],

            "Pahang_median_LFPR":
                year_data[
                    "participation_rate_pct"
                ].median()
        })

bera_comparison = pd.DataFrame(
    bera_comparison
)

bera_comparison.round(3)

"""## Bera Anomaly Investigation

Bera was examined as a potential anomaly because its poverty rate increased substantially between 2019 and 2022 and remained elevated in 2024.

In 2024, Bera recorded an absolute poverty rate of 9.0%, compared with the Pahang district median of 7.9%. However, its unemployment rate was 2.8%, while the corresponding Pahang district median was 1.9%.

At the same time, Bera's labour force participation rate was 53.9%, substantially below the Pahang district median of 63.7%.

This observation is therefore not treated as a data error. Instead, it represents an economically important case in which relatively low unemployment coexists with high poverty and low labour force participation.

The Bera observation provides preliminary evidence that unemployment alone may not adequately capture household economic hardship.
"""

# Initial pooled correlation matrix

correlation_variables = [
    "poverty_absolute_pct",
    "unemployment_rate_pct",
    "participation_rate_pct",
    "labour_force_000",
    "employed_000",
    "unemployed_000",
    "employment_pop_ratio_pct",
    "income_mean_rm",
    "income_median_rm"
]

pooled_corr = analysis_df[
    correlation_variables
].corr()

pooled_corr.round(3)

# Visualise the pooled correlation matrix

import matplotlib.pyplot as plt

plt.figure(figsize=(11, 8))

plt.imshow(
    pooled_corr,
    aspect="auto"
)

plt.colorbar(label="Correlation")

plt.xticks(
    range(len(correlation_variables)),
    correlation_variables,
    rotation=45,
    ha="right"
)

plt.yticks(
    range(len(correlation_variables)),
    correlation_variables
)

plt.title("Initial Pooled Correlation Matrix")

plt.tight_layout()
plt.show()

"""## Initial Pooled Correlation Analysis

The initial Pearson correlation matrix provides an exploratory assessment of the relationships between household poverty and employment-related indicators across the 33 district-year observations.

Absolute poverty showed the strongest negative association with mean household income (r = -0.614), followed by labour force participation rate (r = -0.564) and employment-population ratio (r = -0.562). Median household income also demonstrated a moderate negative association with poverty (r = -0.501).

In contrast, unemployment rate showed almost no linear association with absolute poverty (r = -0.020). This preliminary finding suggests that unemployment rate may be a poor standalone representation of household economic hardship.

The correlation matrix also revealed very strong relationships between several employment indicators. Labour force participation rate and employment-population ratio were highly correlated (r = 0.998), while labour force and employed population were almost perfectly correlated (r = 1.000). Therefore, these indicators should not automatically be included together in the District Vulnerability Index, as they may capture overlapping dimensions of labour-market conditions.
"""

from scipy.stats import pearsonr, spearmanr, kendalltau

# Remove missing values
unemployment_data = analysis_df[
    ["unemployment_rate_pct", "poverty_absolute_pct"]
].dropna()

lfpr_data = analysis_df[
    ["participation_rate_pct", "poverty_absolute_pct"]
].dropna()


# --------------------------------------------------
# 1. UNEMPLOYMENT RATE vs POVERTY
# --------------------------------------------------

pearson_unemp, p_pearson_unemp = pearsonr(
    unemployment_data["unemployment_rate_pct"],
    unemployment_data["poverty_absolute_pct"]
)

spearman_unemp, p_spearman_unemp = spearmanr(
    unemployment_data["unemployment_rate_pct"],
    unemployment_data["poverty_absolute_pct"]
)

kendall_unemp, p_kendall_unemp = kendalltau(
    unemployment_data["unemployment_rate_pct"],
    unemployment_data["poverty_absolute_pct"]
)


# --------------------------------------------------
# 2. LFPR vs POVERTY
# --------------------------------------------------

pearson_lfpr, p_pearson_lfpr = pearsonr(
    lfpr_data["participation_rate_pct"],
    lfpr_data["poverty_absolute_pct"]
)

spearman_lfpr, p_spearman_lfpr = spearmanr(
    lfpr_data["participation_rate_pct"],
    lfpr_data["poverty_absolute_pct"]
)

kendall_lfpr, p_kendall_lfpr = kendalltau(
    lfpr_data["participation_rate_pct"],
    lfpr_data["poverty_absolute_pct"]
)


# --------------------------------------------------
# CREATE SUMMARY TABLE
# --------------------------------------------------

correlation_summary = pd.DataFrame({

    "Indicator": [
        "Unemployment Rate",
        "Labour Force Participation Rate"
    ],

    "Pearson_r": [
        pearson_unemp,
        pearson_lfpr
    ],

    "Pearson_p": [
        p_pearson_unemp,
        p_pearson_lfpr
    ],

    "Spearman_rho": [
        spearman_unemp,
        spearman_lfpr
    ],

    "Spearman_p": [
        p_spearman_unemp,
        p_spearman_lfpr
    ],

    "Kendall_tau": [
        kendall_unemp,
        kendall_lfpr
    ],

    "Kendall_p": [
        p_kendall_unemp,
        p_kendall_lfpr
    ]
})

correlation_summary.round(4)